# Generated by Django 4.0.3 on 2022-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='lat',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='residue',
            name='lon',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
