# Generated by Django 4.0.3 on 2022-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_residue_lat_residue_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
